name: Notebook template

on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Build app on Ubuntu
    uses: octodemo/colind-reusable-workflows/.github/workflows/dotnetbuild.yml@main
    with:
      runs-on: ubuntu-latest