name: Notebook CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - name: Download Artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: notebook-github-ci.yml
        name: artifacts
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .