name: Notebook dev CI

on:
  pull_request:
    types: [opened, reopened]
    branches:  
      - 'dev'   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Environment / Context
      run: |
        env | sort
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Build wheel package
      run: |
        python setup.py bdist_wheel --universal
    - name: copy libs and notebooks
      run: |
        mkdir artifacts 
        cp -r ./dist ./artifacts/libs
        cp -r ./notebook_jobs ./artifacts/notebook_jobs
        cp requirements.txt ./artifacts
        cp setup.py ./artifacts
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts
    - name: Run Unit tests
      run: |
        pytest common/tests --cov 

  deploy-dev:
    name: DEV
    uses: ./.github/workflows/template_deploy_libs_notebooks.yml
    with:
      runs-on: ubuntu-latest
      env: DEV
      DATABRICKS_NOTEBOOK_PATH: /Shared/notebook-tests/dbxbuild_${{github.run_number}}/
    secrets: inherit
    needs: build
