name: Notebook CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1 
    - name: Environment / Context
      run: |
        env | sort
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Run Unit tests
      run: |
        pytest common/tests --cov
    - name: Create Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Notebook-build
        path: Notebook-build