name: Notebook ci use template

on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Build app on Ubuntu
    uses: ./.github/workflows/notebook_template.yml
    with:
      runs-on: ubuntu-latest