name: Reusable workflow

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest

jobs:
  do-it:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!