name: Notebook CD

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: ./.github/workflows/notebook_template.yml

  job2:
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
    - uses: ./.github/workflows/notebook_template.yml