name: Notebook CD

on:
  workflow_dispatch:

jobs:
  job1:
    environment: DEV
    uses: ./.github/workflows/notebook_template.yml

  job2:
    environment: STAGING
    uses: ./.github/workflows/notebook_template.yml    

  job3:
    environment: PROD
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}