name: Notebook CD

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: ./.github/workflows/notebook_template.yml
      with: 
        name: OctoCat

  job2:
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
    - uses: ./.github/workflows/notebook_template.yml
      with: 
        name: OctoCat    

  job3:
    runs-on: ubuntu-latest
    environment: PROD
    needs: job1
    steps:
    - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}