name: Notebook CD with Template

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    name: DEV
    uses: ./.github/workflows/template_deploy_libs_notebooks.yml
    with:
      runs-on: ubuntu-latest
      env: DEV
      DATABRICKS_NOTEBOOK_PATH: /Shared/notebook-tests/dbxbuild_${{github.run_number}}/
    secrets: inherit
  deploy-staging:
    needs: deploy-dev
    name: STAGING
    uses: ./.github/workflows/template_deploy_libs_notebooks.yml
    with:
      runs-on: ubuntu-latest
      env: STAGING
      DATABRICKS_NOTEBOOK_PATH: /Shared/notebook-tests/dbxbuild_${{github.run_number}}/
    secrets: inherit    
  deploy-produciton:
    needs: deploy-staging
    name: production
    uses: ./.github/workflows/template_deploy_libs_notebooks.yml
    with:
      runs-on: ubuntu-latest
      env: produciton
      DATABRICKS_NOTEBOOK_PATH: /Shared/notebooks-release/
    secrets: inherit    