name: Notebook CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1 
    - name: Environment / Context
      run: |
        env | sort
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
      env:
        CI: true
      
    - name: Run Unit tests
      run: |
        pytest common/tests --cov